---
- name: create redis dirs
  file:
    path="{{ item|safe|trim }}"
    state=directory
    owner="{{ redis_user }}"
    group="{{ redis_group }}"
    mode=777
    recurse=yes
  changed_when: "False"
  with_items:
    - "{{ redis_server_opt_dir }}"
    - "{{ redis_server_log_dir }}"
    - "{{ redis_server_config_dir }}"
    - "{{ redis_server_data_dir }}"
  tags:
    - redis
    - redis-install
    - redis-cluster

- name: create redis configuration file
  template:
     dest="{{ redis_server_config_dir }}/{{ item | basename }}"
     owner="{{ redis_user }}"
     group="{{ redis_group }}"
     mode=777
     src={{ item }}
  with_items:
    - redis_server.conf
  register: config_change
  tags:
    - redis
    - redis-install
    - redis-cluster
    - redis-user
    - redis-config
    - redis-config-main

- name: restart redis
  shell: /bin/true
  notify: restart docker-compose-redis-server
  when: ( config_change is defined and config_change.changed )
