---
- name: setup group
  group: name="{{ redis_group }}" system=no
  tags:
    - redis
    - redis-install
    - redis-cluster
    - redis-user

- name: setup user
  user: name="{{ redis_user }}" system=no group="{{ redis_group }}"
  tags:
    - redis
    - redis-install
    - redis-cluster
    - redis-user
