pipeline:
  build:
    image: gentitope/ansible-test-docker:1.2
    pull: true
    commands:
      - git show --pretty="" --no-commit-id  --diff-filter=AMRC  --name-only `git log --format="%H" -n 1` | grep -e .yml$  | tr -s "\n" " " | sed 's/%$//' | xargs ansible-review
        #- git show --pretty="" --no-commit-id  --diff-filter=AMRC  --name-only `git log --format="%H" -n 1` | grep -e .yml$  | tr -s "\n" " " | sed 's/%$//' | xargs -r ansible-lint

  deploy:
    ansible:
      image: gentitope/ansible-test-docker:1.2
      playbook: dev-api-backend.yml