---
pipeline:
  test:
    image: anmolnagpal/devops-ci:0.0.1
    pull: true
    commands:
      - git show --pretty="" --no-commit-id  --diff-filter=AMRC  --name-only `git log --format="%H" -n 1` | grep -e .yml$  | tr -s "\n" " " | sed 's/%$//' | xargs ansible-review

  deploy_test:
    image: anmolnagpal/devops-ci:0.0.1
    pull: true
    commands:
      - ansible-playbook -i localtest/inventory -c local localtest/ci-test.yml -vvv --syntax-check
      - ansible-playbook -i localtest/inventory ./localtest/ci-test.yml --connection=local -vvv
