pipeline:
  build:
    image: yokogawa/ansible-lint
    pull: true
    commands:
        - ansible-lint dev-api-backend.yml
        - ansible-playbook -i ./roles/docker/tests/inventory tests/test.yml --syntax-check

  notify-slack-releases:
    image: plugins/slack
    channel: general
    webhook: https://hooks.slack.com/services/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
    username: Drone-CI
