pipeline:
  build:
    image: gentitope/ansible-test-docker:1.0
    pull: true
    commands:
        - changedfiles=$(git show --pretty="" --no-commit-id  --diff-filter=AMRC  --name-only `git log --format="%H" -n 1` | grep -e .yml$  | tr -s "\n" " " | sed 's/%$//')
        #- ansible-review $changedfiles
        - ansible-lint dev-api-backend.yml