---
pipeline:
  test:
    image: gentitope/ansible-test-docker:1.2
    pull: true
    commands:
      - git show --pretty="" --no-commit-id  --diff-filter=AMRC  --name-only `git log --format="%H" -n 1` | grep -e .yml$  | tr -s "\n" " " | sed 's/%$//' | xargs ansible-review
      - git show --pretty="" --no-commit-id  --diff-filter=AMRC  --name-only `git log --format="%H" -n 1` | grep -e .yml$  | tr -s "\n" " " | sed 's/%$//' | xargs ansible-lint

  deploy_test:
    image: gentitope/ansible-test-docker:1.2
    pull: true
    commands:
      - ansible-playbook -i localtest/inventory -c local find ./playbooks -maxdepth 1 -name '*.yml'| xargs -n1  ansible-playbook --syntax-check --list-tasks -i tests/ansible_hostslocaltest/ci-test.yml
      - ansible-playbook -i localtest/inventory -c local localtest/ci-test.yml --syntax-check --list-tasks