---
- name: installing packages
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=present"
  with_items:
    - python-setuptools

- name: installing dependencies
  easy_install:
    name: pip

- name: remove python modules for docker
  pip:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker-py

- name: install certain python modules for docker
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
    - name: docker-compose
      version: "{{ docker_compose_version | default(omit) }}"
    - name: docker
      version: "{{ docker_pip_version | default(omit) }}"

- name: setup group
  group: name=test3 system=yes
  tags:
    - test

- name: setup user
  user: name=test3 system=yes group=test3
  tags:
    - test
